import { Inter, Josefin_Sans } from 'next/font/google';
import './globals.css';

import { AppContextProvider } from '@/app/contexts/AppContext';
import Navbar from '@/app/components/Navbar/Navbar';
import Footer from './components/Footer/Footer';

const inter = Inter({ subsets: ['latin'] });
const JosefinSans = Josefin_Sans({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={JosefinSans.className}>
        <AppContextProvider>
          <Navbar />
          {children}
          <Footer/>
        </AppContextProvider>
      </body>
    </html>
  );
}
